# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Release next packages

on:
  push:
    branches:
      - next

jobs:
  publish:
    name: Publish next packages to NPM

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      RAW_COMMIT_MESSAGE: 'chore: release next package(s)'

    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ•º Setup Node.js and pnpm
        uses: oven-sh/setup-bun@v2

      - name: ðŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ðŸ”¨ Build
        run: bun run build --filter !@elysiajs/documentation

      - name: âœï¸ Generate commit message
        id: devmoji
        run: |
          MESSAGE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(env.RAW_COMMIT_MESSAGE) }})
          echo "MESSAGE=$MESSAGE" >> $GITHUB_OUTPUT

      - name: ðŸš€ Create pull request or publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: bun changeset publish
          commit: ${{ steps.devmoji.outputs.MESSAGE }}
          title: ${{ steps.devmoji.outputs.MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
